apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: prometheus-pushgateway
    targetRevision: 2.17.0
    helm:
      valuesObject:
        service:
          type: ClusterIP
          port: 9091

        # важно, чтобы Prometheus Operator увидел таргет
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

